"""add link table

Revision ID: 20906028dfa4
Revises: c04b35ba1ec5
Create Date: 2024-11-18 23:59:53.985020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20906028dfa4'
down_revision: Union[str, None] = 'c04b35ba1ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_vault_collections',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the collection'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='Title of the collection'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='Description of the collection'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Identifier of the user who owns the collection'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Created time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Updated time'),
    sa.ForeignKeyConstraint(['user_id'], ['link_vault_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Represents a user collection in the system'
    )
    op.create_table('link_vault_links',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the link'),
    sa.Column('page_title', sa.String(length=64), nullable=False, comment='Title of the page'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='Description of the page'),
    sa.Column('link', sa.String(length=256), nullable=False, comment='Link of the page'),
    sa.Column('image_url', sa.String(length=256), nullable=True, comment='Image URL of the page'),
    sa.Column('link_type', sa.Enum('website', 'book', 'article', 'music', 'video', name='linktype'), nullable=False, comment='Type of the link'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Identifier of the user associated with the link'),
    sa.Column('collection_id', sa.UUID(), nullable=True, comment='Identifier of the collection associated with the link'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Created time'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Updated time'),
    sa.ForeignKeyConstraint(['collection_id'], ['link_vault_collections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['link_vault_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'link', name='uq_user_link'),
    comment='Represents a user link in the system'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_vault_links')
    op.drop_table('link_vault_collections')
    # ### end Alembic commands ###
