"""add user id to associations

Revision ID: e8425735afd6
Revises: ff21f5f20905
Create Date: 2024-11-19 22:11:10.360027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8425735afd6'
down_revision: Union[str, None] = 'ff21f5f20905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_vault_link_collection_associations', sa.Column('user_id', sa.UUID(), nullable=False, comment='Identifier of the user'))
    op.drop_constraint('uq_link_collection', 'link_vault_link_collection_associations', type_='unique')
    op.create_unique_constraint('uq_link_collection', 'link_vault_link_collection_associations', ['link_id', 'collection_id', 'user_id'])
    op.create_foreign_key(None, 'link_vault_link_collection_associations', 'link_vault_users', ['user_id'], ['id'])
    op.create_table_comment(
        'link_vault_link_collection_associations',
        '',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'link_vault_link_collection_associations',
        existing_comment='',
        schema=None
    )
    op.drop_constraint(None, 'link_vault_link_collection_associations', type_='foreignkey')
    op.drop_constraint('uq_link_collection', 'link_vault_link_collection_associations', type_='unique')
    op.create_unique_constraint('uq_link_collection', 'link_vault_link_collection_associations', ['link_id', 'collection_id'])
    op.drop_column('link_vault_link_collection_associations', 'user_id')
    # ### end Alembic commands ###
